name: 3 Delete EKS Cluster, Prefect agent and ECR repository

on:
  workflow_dispatch:

env:
  PROJECT: prod

jobs:
  delete-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Delete ECR repository
        continue-on-error: true
        run: |
          aws ecr delete-repository --repository-name ${{ env.PROJECT }} --force
          aws cloudformation delete-stack --stack-name "${{ env.PROJECT }}-ecr"

      - name: Delete EKS node group
        continue-on-error: true
        run: aws cloudformation delete-stack --stack-name eksctl-prefect-nodegroup-prefect-ng-1

      - name: Delete EKS IAM service account
        continue-on-error: true
        run: aws cloudformation delete-stack --stack-name eksctl-prefect-addon-iamserviceaccount-kube-system-aws-node

      - name: Delete EKS agent service
        continue-on-error: true
        run: aws cloudformation delete-stack --stack-name eksctl-prefect-cluster

      - name: All AWS resources deleted
        run: echo '### All AWS resources deleted! :tada:' >> $GITHUB_STEP_SUMMARY
