name: Delete AWS EKS Cluster

on:
  workflow_dispatch:

env:
  EKS_CLUSTER: prefect

jobs:
  delete-stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Install eksctl
        run: |
          brew tap weaveworks/tap
          brew install weaveworks/tap/eksctl
          echo "ekctl istalled with version: $(eksctl version)" >> $GITHUB_STEP_SUMMARY

      - name: Delete EKS cluster
        run: eksctl delete cluster --name ${{env.EKS_CLUSTER}}
  # or: eksctl delete cluster -f infrastructure/cluster.yml
